### ISSUE TITLE
Failed to execute script 'run' due to unhandled exception!

### ISSUE THREAD

**Issue by yangxucs1** [kerm-me/docdown#16]
报错，恳请大佬看下是啥原因
内容如下：
Traceback (most recent call last):
  File "run.py", line 6, in <module>
  File "tool.py", line 133, in download_from_url
UnboundLocalError: local variable 'imagepath' referenced before assignment
[7608] Failed to execute script 'run' due to unhandled exception!

文档链接：https://jz.docin.com/p-3838235831.html?building=1&fid=5051&sid=0

**Comment by Alitterman** [comment]
set PLAYWRIGHT_BROWSERS_PATH=0
playwright install webkit
安装 webkit，然后使用 pyinstaller 打包文件run.py。

参考：[playwright在pyinstaller下打包](https://www.52pojie.cn/thread-1598055-1-1.html)

**Comment by yangxucs1** [comment]
谢谢大佬的回复，我试试看
