### ISSUE TITLE
使用pyinstaller打包的问题

### ISSUE THREAD

**Issue by likemuuxi** [kerm-me/docdown#9]
打包成exe后，运行后出现错误，找不到playwright模块，但在conda的虚拟环境中已经安装，想问下作者打包时是否出现此问题

**Comment by kerm-me** [comment]
参考 https://www.52pojie.cn/thread-1598055-1-1.html

**Comment by likemuuxi** [comment]
> 参考 https://www.52pojie.cn/thread-1598055-1-1.html

按照如下步骤尝试了，结果还是不行，

playwright install
set PLAYWRIGHT_BROWSERS_PATH=0    
playwright install webkit   
pyinstaller -F run.py --noconsole

在run.py下写了个简单GUI界面，作者能否帮忙打包一下呢

`import PySimpleGUI as sg
import tool

sg.theme('TanBlue')  #sg.theme('Reddit')   #  Dark Blue 3

def main():
    menu_def =[['&帮助', ['&使用说明']]]
    layout = [
        [sg.Menu(menu_def, key='-MENU-', tearoff=False, pad=(200, 1))],
        [
            sg.Text('请输入下载链接：', size=(15, 1)),
            sg.InputText('',key='-url-', size=(45, 1)),
        ],
        [    sg.Button('下载', button_color=('white', 'firebrick1')),
            sg.Button('退出', button_color=('white', 'firebrick3')),
        ]
    ]

    window = sg.Window('豆丁、原创力文档下载', layout)
    while True:
        event, values = window.read()
        if event in ('退出', None):
            break
        if event == '下载':
            try:
                url = values['-url-']
                tool.download_from_url(url)
                sg.popup('下载完毕!')
            except:
                sg.popup('已取消!')
        if event == '使用说明':
            sg.popup(
                    '部分文档格式不支持。',
                    '需要付费预览的文档不支持。',
                    '只支持下载为 PDF 格式（image 转 pdf）。',
                    '百度文库清晰度较低（Playwright 截图限制）。'
                    )
    window.close()
if __name__ == '__main__':
    main()`
